[preset]
name = "default"
version = "1.0.0"
description = "Default Claude Code configuration with recommended settings"

[[components]]
type = "claude_md"
name = "default"
path = "CLAUDE.md"
enabled = true

[[components]]
type = "gitignore"
name = "standard"
path = ".gitignore"
enabled = true

[[components]]
type = "settings_json"
name = "default"
path = ".claude/settings.json"
enabled = true

[[components]]
type = "commands"
name = "example"
path = ".claude/commands/"
enabled = true

[[components]]
type = "agents"
name = "example"
path = ".claude/agents/"
enabled = true

[[components]]
type = "hooks"
name = "example"
path = ".claude/hooks/"
enabled = true

[[components]]
type = "mcp"
name = "example-github"
path = ".claude/mcp/"
enabled = true

[[components]]
type = "mcp"
name = "example-memory"
path = ".claude/mcp/"
enabled = true

[[components]]
type = "output_styles"
name = "example"
path = ".claude/output-styles/"
enabled = true

[[components]]
type = "statusline"
name = "default"
path = ".claude/statusline.sh"
enabled = true

[[components]]
type = "settings_local_json"
name = "default"
path = ".claude/settings.local.json"
enabled = true
